name: generate-github-profile-3d-contrib

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *" 
  workflow_dispatch:
  # run on every push on the master branch
  push:
    branches:
    - main




jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      
      - name: push generate-github-profile-3d-contrib to the profile-3d-contrib branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: profile-3d-contrib
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
